### ISSUE TITLE
Relocate datasetregister

### ISSUE THREAD

**Issue by coret** [netwerk-digitaal-erfgoed/infrastructure#19]
The datasetregister - demonstrator and API -  should be available via datasetregister.netwerkdigitaalerfgoed.nl

- set DNS A record for datasetregister as subdomain of netwerkdigitaalerfgoed.nl (IP=178.128.138.52)  @EnnoMeijers 
- change infrastructure configuration in order to make register-demo (and register-api) available via datasetregister.netwerkdigitaalerfgoed.nl (and datasetregister.netwerkdigitaalerfgoed.nl/api) @ddeboer 
- add (permanent) redirect from old address http://demo.netwerkdigitaalerfgoed.nl/register to new address @ddeboer

**Comment by EnnoMeijers** [comment]
Request for 'datasetregister' as a new subdomain for 178.128.138.52 has been sent to our DNS provider. I will keep you posted.

**Comment by ddeboer** [comment]
Done.
