### ISSUE TITLE
Improve (re)start of GeoNames SPARQL server

### ISSUE THREAD

**Issue by ddeboer** [netwerk-digitaal-erfgoed/infrastructure#38]
We now have a StatefulSet, because DigitalOcean block storage only supports ReadWriteOnce.

When the StatefulSet is restarted, its InitContainer will spin up, which imports GeoNames data and takes rather long. With StatefulSets, the old one is deleted before the next one started.

Can we use a Deployment instead? Each deployment replica would have its own storage, but that should be fine.

We could only trigger the cronjob manually, but then the Fuseki SPARQL server still needs to be restarted to reload the data.

**Comment by EnnoMeijers** [comment]
We could also improve the map.sh for example to write to a temp file and copy this to the Fuseki server when the mapping task has finished.
