### ISSUE TITLE
Add prototypes

### ISSUE THREAD

**Issue by ddeboer** [netwerk-digitaal-erfgoed/infrastructure#43]
- [x] [heritageflix-churches.demo.netwerkdigitaalerfgoed.nl](http://heritageflix-churches.demo.netwerkdigitaalerfgoed.nl/) @GertjanFi will let us know which branch should be deployed here
- [ ] [heritageflix-paintings.demo.netwerkdigitaalerfgoed.nl](http://heritageflix-paintings.demo.netwerkdigitaalerfgoed.nl/) @GertjanFi will let us know which branch should be deployed here
- [x] [gvn.demo.netwerkdigitaalerfgoed.nl](http://gvn.demo.netwerkdigitaalerfgoed.nl/) 
- [ ] [modemuze.demo.netwerkdigitaalerfgoed.nl](http://modemuze.demo.netwerkdigitaalerfgoed.nl/) @sdevalk @GertjanFi What do you want to deploy here?
- [x] [datasetbrowser.demo.netwerkdigitaalerfgoed.nl](http://datasetbrowser.demo.netwerkdigitaalerfgoed.nl/) Blocked by https://github.com/netwerk-digitaal-erfgoed/dataset-browser/issues/1
- [x] [datastories.demo.netwerkdigitaalerfgoed.nl](http://datastories.demo.netwerkdigitaalerfgoed.nl/) @EnnoMeijers What do we want to deploy here?

**Comment by GertjanFi** [comment]
- heritageflix-churches.demo.netwerkdigitaalerfgoed.nl: daar releasen we https://github.com/netwerk-digitaal-erfgoed/heritageflix/tree/churchflix heen
- http://heritageflix-paintings.demo.netwerkdigitaalerfgoed.nl/: daar releasen we https://github.com/netwerk-digitaal-erfgoed/heritageflix heen -> de default branch (dat ding heet develop)
- http://modemuze.demo.netwerkdigitaalerfgoed.nl/ -> die discussie loopt nog - we gaan in ieder geval niets releasen op dit subdomein. Ik zou een forward willen zien naar of een page op de modemuze-website (waar de drie data stories staan gelinkt). Of naar de urls van de eerste overkoepelende data story bij Triply (die moet dan ook verwijzen naar de andere twee en ik moet even checken of Triply een persistent url heeft voor data stories)

**Comment by EnnoMeijers** [comment]
To create an convenient index to demo/protype applications we should extend https://github.com/netwerk-digitaal-erfgoed/demo-frontend (and remove the current register entry) . 

 The existing datastories entry in the demo-frontend points currently to demo.netwerkdigitaalerfgoed.nl/stories which runs the stories https://github.com/netwerk-digitaal-erfgoed/stories app. I would like to see this moved to datastories.demo.netwerkdigitaalerfgoed.nl.

**Comment by GertjanFi** [comment]
Just fixed https://github.com/netwerk-digitaal-erfgoed/dataset-browser/issues/1

The page now shows a 502-Bad Gateway thrown by nginx. Is that me/the dockerfile or you (@ddeboer)?

**Comment by GertjanFi** [comment]
@ddeboer change for:

http://heritageflix-paintings.demo.netwerkdigitaalerfgoed.nl/

I requested the devs to switch away from the `develop` branch and they just did, please release the branch: `https://github.com/netwerk-digitaal-erfgoed/heritageflix/tree/paintingsflix`

**Comment by ddeboer** [comment]
> * http://modemuze.demo.netwerkdigitaalerfgoed.nl/ -> still discussed - there won't be any deployment here. I'd like to have a forward to either a page on the Modemuze-website (it will contain links to the three data stories) or to the URL of the first 'main' data story at Triply. That story will then link to the two more detailed stories. I do still have to check if Triply supports persistent URLs for data stories.

Closing this issue as all apps are now running on our infrastructure. Please create a separate issue (or e-mail me) when  details are known about Modemuze.
