### ISSUE TITLE
Create an index page for demo.netwerkdigitaalerfgoed.nl

### ISSUE THREAD

**Issue by EnnoMeijers** [netwerk-digitaal-erfgoed/infrastructure#45]
Currently https://demo.netwerkdigitaalerfgoed.nl results in a 404. I suggest to create an index page similar to previous https://github.com/netwerk-digitaal-erfgoed/demo-frontend to introduce the available demo's and prototypes that can be found here.

**Comment by EnnoMeijers** [comment]
I updated the demo-frontend configuration see PR https://github.com/netwerk-digitaal-erfgoed/demo-frontend/pull/21. This version can be used as the index page at demo.netwerkdigitaalerfgoed.nl.

**Comment by ddeboer** [comment]
@EnnoMeijers The 404 is due to DNS for demo.netwerkdigitaalerfgoed no longer properly resolving to our cluster at `178.128.138.52`. Can you ask our DNS provider to fix that? It’s important to keep `*.demo.netwerkdigitaalerfgoed` intact as well.

**Comment by EnnoMeijers** [comment]
demo.netwerkdigitaalerfgoed.nl has been added to the DNS and as far as I can see are the others subdomains still working.

**Comment by ddeboer** [comment]
And so is the new demo site, so that’s good news!
